# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"
vimcmd_symbol =	"[](bold green)" 	# The format string used before the text input if the shell is in vim normal mode.
vimcmd_replace_one_symbol = "[](bold purple)" 	# The format string used before the text input if the shell is in vim replace_one mode.
vimcmd_replace_symbol = "[](bold purple)" 	# The format string used before the text input if the shell is in vim replace mode.
vimcmd_visual_symbol = "[](bold yellow)" 	# The format string used before the text input if the shell is in vim visual mode.

[username]
style_user = "red"
style_root = "blue"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@[$hostname](white) "
disabled = false

[sudo]
disabled = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
style = "green"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = "󰏔 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "
