#! /bin/sh
xrdb -merge ~/.Xressources &
sxhkd &
lxpolkit &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
nm-applet &
blueman-applet &
killall dunst && dunst &
setxkbmap -option compose:rwin
unclutter &
xsetroot -cursor_name left_ptr

#setxkbmap -option caps:swapescape &

#xrandr --output eDP-1 --mode 1920x1080 --pos 2560x360 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal
# feh --bg-fill ~/Images/walls/wall
~/.fehbg &
# feh --bg-fill --randomize ~/Images/walls/* &

#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7
#bspc monitor eDP-1 -d 8 9 0

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           16
bspc config top_padding          27

bspc config normal_border_color "#3b4252"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#bf616a"
bspc config presel_feedback_color "#bf616a"

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Galculator state=floating
bspc rule -a Pulsemixer state=floating

killall pasystray & sleep 2; pasystray &
insync quit && insync start &
