#! /bin/sh
sxhkd &
#xrandr --output eDP-1 --mode 1920x1080 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --rotate normal --above eDP-1
xrandr --output eDP-1 --mode 1920x1080 --pos 2560x360 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal
nitrogen --restore &
$HOME/.config/polybar/launch.sh &


lxpolkit &
picom &
#setxkbmap -option caps:swapescape &
numlockx &
unclutter &
xset +fp /home/mathieu/.local/share/fonts
xset fp rehash
xrdb -merge .Xressources &
xsetroot -cursor_name left_ptr
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           15
bspc config top_padding          27

bspc config normal_border_color "#3b4252"
bspc config active_border_color "#e5e9f0"
bspc config focused_border_color "#bf616a"
bspc config presel_feedback_color "#bf616a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'Gimp-2.10' desktop='^4' follow=on
bspc rule -a Galculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xrandr --output eDP-1 --mode 1920x1080 --pos 2560x360 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal &
#sleep 2 &&
#xrandr --output eDP-1 --mode 1920x1080 --pos 225x1440 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal &

