[general]
fullscreen = true
early-exit = true
initial-tool = "highlight"
copy-command = "wl-copy"
annotation-size-factor = 0.5
output-filename = "/home/mathieu/Images/Screenshots/screenshot-%Y%m%d-%H%M%S.png"
save-after-copy = true
default-hide-toolbars = false
# The primary highlighter to use, the other is accessible by holding CTRL at the start of a highlight [possible values: block, freehand]
primary-highlighter = "freehand"
disable-notifications = false

# Font to use for text annotations
[font]
family = "Inter"
style = "Bold"

# custom colours for the colour palette
[color-palette]
palette = [
"#f8e45c",
"#81a1c1",
"#a3be8c",
"#b48ead",
"#bf616a",
"#ebcb8b",
]
