[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm -e sh -c 'tmux attach -t $(uname -n) || tmux new -s $(uname -n)'"
class = "kitty-dropterm"
animation = ""
size = "60% 70%"
margin = 60
#unfocus = "hide"
lazy = true

[scratchpads.files]
animation = ""
command = "kitty --class kitty-yazi -e yazi"
class = "kitty-yazi"
size = "60% 70%"
margin = 60
#unfocus = "hide"
lazy = true

# [scratchpads.explorer]
# animation = ""
# command = "thunar"
# class = "thunar"
# size = "60% 70%"
# margin = 60
# unfocus = "hide"
# lazy = true

[scratchpads.passwords]
animation = ""
command = "bitwarden-desktop"
class = "Bitwarden"
size = "60% 70%"
margin = 60
# unfocus = "hide"
lazy = true
