### envvar.conf
$terminal = kitty
$webBrowser = firefox
$fileManager = thunar
$accentColor = $frost2
$layout = master
$contour = 3

$screenshotModify = grim - | satty -f -
$screenshotPlain = grim $HOME/Images/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png

$reset = hyprctl dispatch submap reset && # helper variable for submaps
$menu = ~/.config/rofi/launchers/type-2/launcher.sh
$powerMenu = ~/.config/rofi/powermenu/type-3/powermenu.sh
$switchLock = hyprlock --immediate-render & systemctl suspend

### ENVIRONMENT VARIABLES ###
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CURRENT_DESKTOP,GNOME
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,gtk2
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18
