# ctrl+space as leader key
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# vim keys
setw -g mode-keys vi

# force 24 bit colors
set -sa terminal-overrides ",xterm-kitty:Tc"

# limit history to 10000 lines
set -g history-limit 10000

# fix windows title
set -g set-titles on
set -g set-titles-string "#T"

# More friendly split pane
bind-key - split-window -v
bind-key \\ split-window -h

