# ctrl+space as leader key
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# vim keys
setw -g mode-keys vi

# force 24 bit colors
set -sa terminal-overrides ",xterm-kitty:Tc"

# limit history to 10000 lines
set -g history-limit 10000

# fix windows title
set -g set-titles on
set -g set-titles-string "#T"

# More friendly split pane
bind-key - split-window -v
bind-key \\ split-window -h

# Enable mouse support
set -g mouse on

# theme
#source-file "/home/mathieu/.local/github/tmux-themepack/powerline/default/gray.tmuxtheme"

set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#353b49"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#353b49"
set -g @nova-status-style-fg "#d8dee9"
set -g @nova-status-style-active-bg "#b48ead"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#a3be8c #2e3440"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#a3be8c #2e3440"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"
run-shell ~/.local/github/tmux-nova/nova.tmux
