#!/usr/bin/env bash

# --- Shell & System ---
alias c='clear'
alias zz='exec $SHELL'
alias source-bash='source ~/.bashrc'
alias wh='which'
alias line-count="find . -type f ! -path '*/.git/*' | xargs cat | wc -l"

# --- System Info & Monitoring ---
alias ff="fastfetch"
alias dy="touch /mnt/NAS/NFS_MOUNT && touch /mnt/backups/NFS_MOUNT && dysk -c mp+type+size+free+used+use -s size-asc"
alias zsh-255-colors='for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done'

# --- File Operations ---
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'
alias ..='cd ..'
alias untar='tar xvf'
alias less='less --quiet'
alias compress_photos="find . -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -exec mogrify -resize 1920x1080\> -quality 85 {} +"

# --- ls / exa ---
alias ls='eza --group-directories-first --icons=auto'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias ldot='ls -ld .*'

# --- Disk Usage ---
alias df='df --human-readable'
alias du='du --human-readable'

# --- Networking ---
alias ip4='ip -br -c -4 a'
alias ip6='ip -br -c -6 a'
alias mon-ip="curl -s ifconfig.me | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'"

# --- Clipboard Management ---
alias copy="wl-copy"
alias paste="wl-paste"
alias cbc="cliphist list | fzf --no-sort | cliphist decode | wl-copy"
alias cbd="cliphist list | fzf --no-sort | cliphist delete"

# --- Editor & Development Tools ---
alias vim=nvim
alias vv="nvim -c \"lua require('telescope.builtin').find_files()\""

# --- Quick Vim (dotfiles & projects) ---
alias vva="cd $HOME/dotfile; nvim $HOME/dotfiles/zsh/aliases"
alias vvd='cd $HOME/dotfiles; nvim -c "lua require(\"user.telescope_dot\")"'
alias vvv='cd $HOME/dotfile; nvim -c "lua require(\"user.telescope_nvim\")"'
alias vvb='cd $HOME/.local/bin/; nvim -c "lua require(\"user.telescope_bin\")"'
alias vvc='cd $HOME/Projets/rkb/crawler; nvim -c "lua require(\"user.telescope_crawler\")"'

# --- Database Connections ---
alias rkb-db-connect-prod="rainfrog --username postgres --database rkb_db --host 192.168.100.6 --port 5432 --driver postgres --password \$RKB_DB_PASSWORD"
alias rkb-db-connect-local="rainfrog --username postgres --database rkb_db --host localhost --port 5432 --driver postgres --password \$RKB_DB_PASSWORD"

# --- External Tools ---
alias portfolio="ticker --config ~/Coffre/portfolio.yaml"
alias gemini-cli="npx https://github.com/google-gemini/gemini-cli"

# --- Notes/Obsidian ---
alias td="note.sh todo"
alias oh="note.sh home"
alias or="note.sh inbox"
alias on="note.sh new"
alias oj="note.sh journal"
alias ow="note.sh dailies"
alias oq="note.sh quick-switch"
alias os="note.sh grep"
alias ot="note.sh new-from-template"
alias oa="note.sh search-by-tags"

# --- Backups ---
alias bkp-pkglist="rm -f ~/Projets/paclist.txt && paru -Qqe > ~/Projets/paclist.txt"
alias bkp-etc="sudo tar -czf ~/Projets/etc/etc_backup-$(date +%F).tar.gz /etc"
alias bkp-etc-clean="find ~/Projets/etc/ -name 'etc_backup-*.tar.gz' -type f -printf '%T@ %p\n' | sort -rn | tail -n +4 | cut -d' ' -f2- | xargs -r rm -v"
alias bkp-home-btrfs="~/.local/bin/btrfs-backup.sh"
alias bkp="bkp-pkglist && bkp-etc && bkp-etc-clean && bkp-home-btrfs"

# --- Tmux ---
alias t="tmux attach || tmux new -s $(uname -n)"

# --- Docker ---
alias olm="docker exec -it ollama ollama"
alias lzd="lazydocker"

# --- Git ---
alias lzg="lazygit"
alias g="git status"
alias ga="git add"
alias gap="git add --patch"
alias gaa="git add ."
alias gau="git add -u"
alias gc="git commit"
alias gcm="git commit -m"
alias gca="git commit -am"
alias gb="git branch"
alias gbd="git branch -d"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gt="git stash"
alias gta="git stash apply"
alias gm="git merge"
alias gr="git rebase"
alias gl="git log --all --graph --pretty=format:'%C(magenta)%h %C(brightblack)%an %ar%C(auto) %D%n%s%n'"
alias gs="git show"
alias gd="git diff --color --color-words"
alias gdc="git diff --cached"
alias gbl="git blame"
alias gps="git push"
alias gpl="git pull"
alias grmc="git rm -r --cached"

# --- Python ---
alias venv-activate="source .venv/bin/activate"
alias va="venv-activate"

# --- Package Management ---
if [[ "$(uname)" == "Linux" ]]; then
    if [ -f /etc/os-release ]; then
        source /etc/os-release
        if [[ "$ID" == "arch" ]]; then
            # Arch-specific aliases
            alias up="pu"
        elif [[ "$ID" == "debian" || "$ID" == "ubuntu" ]]; then
            # Debian-specific aliases
            alias up="au"
        fi
    fi
fi

# Pacman/Paru
alias pu='paru; pkill -SIGRTMIN+8 waybar; flatpak update'
alias pi='paru -Si'
alias pr='paru -Rs'
alias pl='pacman -Q'
alias ple='pacman -Qe'
alias pla='pacman -Qem'
alias pc='sudo pacman -Scc'
alias sp='parui'

# Apt
alias au='sudo apt update && sudo apt upgrade && sudo apt dist-upgrade && sudo apt autoremove && sudo apt autoclean && sudo apt clean && flatpak update'
alias ai="sudo apt install"
alias ap="sudo apt purge"
alias ar="sudo apt remove"
alias as="apt search"

# Flatpak
alias fp='flatpak'
