#!/usr/bin/env bash
alias c='clear'
alias zz='exec $SHELL'
alias source-bash='source ~/.bashrc'
alias ff="fastfetch"
alias bsh='exec bash -l'
alias wh='which'
alias ..='cd ..'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'
alias less='less --quiet'
alias df='df --human-readable'
alias du='du --human-readable'
alias ls='exa --group-directories-first --icons'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias ldot='ls -ld .*'
alias untar='tar xvf'
alias t-down="sudo tailscale down && sudo systemctl restart autofs.service"
alias t-up="sudo tailscale up"
alias ip4='ip -br -c -4 a'
alias ip6='ip -br -c -6 a'
alias mon-ip="curl -s ifconfig.me | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'"
alias line-count="find . -type f ! -path '*/.git/*' | xargs cat | wc -l"
alias olm="docker exec -it ollama ollama"
alias rkb-db-connect-prod="rainfrog --username postgres --database rkb_db --host 192.168.100.6 --port 5432 --driver postgres --password $RKB_DB_PASSWORD"
alias rkb-db-connect-local="rainfrog --username postgres --database rkb_db --host localhost --port 5432 --driver postgres --password $RKB_DB_PASSWORD"
alias portfolio="ticker --config ~/Coffre/portfolio.yaml"
alias ppc="cliphist list | fzf --no-sort | cliphist decode | wl-copy"
alias ppd="cliphist list | fzf --no-sort | cliphist delete"

alias vim=nvim

# quick vim
alias dot='cd $HOME/dotfiles && nvim -c "lua require(\"user.telescope_dot\")"'
alias dtv='cd $HOME/dotfile && nvim -c "lua require(\"user.telescope_nvim\")"'
alias dta="cd $HOME/dotfile && nvim $HOME/dotfiles/zsh/aliases"
alias vv="nvim -c \"lua require('telescope.builtin').find_files()\""

# obsidian/notes
alias td="note.sh todo"
alias oh="note.sh home"
alias or="note.sh inbox"
alias on="note.sh new"
alias oj="note.sh journal"
alias ow="note.sh dailies"
alias oq="note.sh quick-switch"
alias os="note.sh grep"
alias ot="note.sh new-from-template"
alias oa="note.sh search-by-tags"

alias pkglist="rm -f ~/Projets/paclist.txt && paru -Qqe > ~/Projets/paclist.txt"
alias bkp="~/.local/bin/btrfs-backup.sh"
alias etc-bkp="sudo tar -czf ~/Projets/etc/etc_backup-$(date +%F).tar.gz /etc"

alias t="tmux attach || tmux new -s $(uname --nodename)"
alias tn='export TMUX_SESSION_NAME="$(date +%d%H%M%S)" && tmux new-session -d -s "$TMUX_SESSION_NAME" && tmux switch-client -t "$TMUX_SESSION_NAME"'
alias ta="tmux attach"
alias tl="tmux ls"
alias ts="tmux attach -t"

alias z="zellij attach || zellij"
alias za="zellij attach"
alias zl="zellij list-sessions"
alias zs="zellij --session"

alias date-computer='date +"%Y-%m-%d_%H:%M:%S"'
alias date-human='date +"%A %d %B %Y, %H:%M"'

# docker
alias lzd="lazydocker"

# git
alias lzg="lazygit"
alias g="git status"
alias ga="git add"
alias gaa="git add ."
alias gau="git add -u"
alias gc="git commit -m"
alias gca="git commit -am"
alias gb="git branch"
alias gbd="git branch -d"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gt="git stash"
alias gta="git stash apply"
alias gm="git merge"
alias gr="git rebase"
alias gl="git log --oneline --decorate --graph"
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias glga="git log --graph --oneline --all --decorate"
alias gs="git show"
alias gd="diff --color --color-words --abbrev"
alias gdc="git diff --cached"
alias gbl="git blame"
alias gps="git push"
alias gpl="git pull"
alias gk="gitk --all&"
alias gx="gitx --all"
alias grmc="git rm -r --cached"

# swap esc & caps lock (Xorg)
# alias se="setxkbmap -option caps:swapescape"
# alias sb="setxkbmap -option"

# Python
# alias venv-mk="python3 -m venv venv"
# alias vmk="venv-mk"
alias venv-activate="source .venv/bin/activate"
alias va="venv-activate"

# pbcopy/paste like (Xorg)
# alias cbcopy='xsel --clipboard --input'
# alias cbpaste='xsel --clipboard --output'

alias copy="wl-copy"
alias paste="wl-paste"

# Gestion des paquets

alias up="pu"
# Pacman
alias pu='paru; pkill -SIGRTMIN+8 waybar'
alias pi='paru -Si'         #   install
alias pr='paru -Rs'         #   remove
alias pl='pacman -Q'        #   list installed
alias ple='pacman -Qe'      #   list explicitly installed
alias pla='pacman -Qem'     #   list explicitly installed packages from the AUR
alias pc='sudo pacman -Scc' #   clean cache

# Apt
alias au='sudo apt update && sudo apt upgrade && sudo apt dist-upgrade && sudo apt autoremove && sudo apt autoclean && sudo apt clean && flatpak update'
alias ai="sudo apt install"
alias ap="sudo apt purge"
alias ar="sudo apt remove"
alias as="apt search"

# Flatpak
alias fp='flatpak'
